import fs from 'fs';
import lodash from 'lodash';
import { Message } from './Message';

class App {
    myId = 'user718097882';

    run() {
        const dictionary: {[word: string]: number} = {};

        const messages: Message[] = JSON.parse(
            fs.readFileSync('./telegram-data/result.json').toString()
        ).messages;
        console.log('Total messages: ' + messages.length);
        const parsedMessages: string[][] = [];
        for (const message of messages) {
            if (message.from_id == this.myId && message.text) {
                const words = getWords(message.text);
                for (const word of words) {
                    dictionary[word] = (dictionary[word] || 0) + 1;
                }
                parsedMessages.push(words);
            }
        }
        const sortedDictionary = lodash.sortBy(Object.entries(dictionary), entry => entry[1])
            .reverse()
            .filter(w => w[0] != '.');
        console.log(sortedDictionary);

        const topWords = sortedDictionary.slice(0, 100).map(entry => entry[0]);
        let sourceText = '// Data generated by the builder\n';
        sourceText += 'export const TOP_WORDS = ' + JSON.stringify(topWords) + ';\n'
        const topMessages = parsedMessages.filter(message => topWords.some(w => message.includes(w)));
        console.log('Top messages: ' + topMessages.length);
        sourceText += 'export const MESSAGES = ' + JSON.stringify(topMessages, null, '    ') + ';'
        fs.writeFileSync('../chatbot/src/data/topWords.ts', sourceText);
    }
}

function getWords(text: string) {
    const words: string[] = [];
    let word = '';
    for (const character of text) {
        if (isLetter(character))
            word += character;
        else if (word.length) {
            words.push(word.toLowerCase());
            word = '';
        }
        if (isChainBreaker(character))
            if (words.length && isLetter(words[words.length - 1]))
                words.push('.');
    }
    if (word.length)
        words.push(word.toLowerCase());
    if (words.length && words[words.length - 1] == '.')
        words.pop();
    return words;
}

function isLetter(text: string) {
    return text.toString().toLowerCase() != text.toString().toUpperCase();
}

function isChainBreaker(text: string) {
    return [';', '.', ':', '!', '?'].includes(text);
}

new App().run();